describe('Start model tests...', () => {
  require('./comment.model.test')
  require('./comment-read.model.test')
  require('./device.model.test')
  require('./activity.model.test')
  require('./collaboration-invite.model.test')
  require('./comment-spam.model.test')
  require('./page-spam.model.test')
  require('./story-spam.model.test')
  require('./group.model.test')
  require('./group-invite.model.test')
  require('./following.model.test')
  require('./forgot-password.model.test')
  require('./author.model.test')
  require('./story.model.test')
  require('./page.model.test')
  require('./favorite.model.test')
})
