describe('Start API tests...', () => {
  // require('./test-server')
  require('./authors')
  require('./collaboration')
  require('./stories')
  require('./page')
  require('./following')
  require('./export')
  require('./spam')
  require('./device')
  require('./activities')
  require('./comments')
  require('./group')
})
